name: first workflow

env:
  WORKFLOW_VAR: "this is a workflow lvl variable"

on:
  workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! This is the first job
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }}
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time }}"
        
 
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env: 
      JOB_VAR: "Ths is a job var"
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second job
          echo and this is a multi-line script
      - name: environment variable
        env:
          STEP_VAR: "This is a step lvl variable"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "The following is a secret: ${{ secrets.SOME_SECRET }}"
          echo $GITHUB_ACTOR
          
